QuTech-Delft/quantuminspire

- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
We can support this, but for now disable it to pass tests. Follow-up
ticket is defined (DEM-737) to implement returning the raw
measurements.
> [DEM-NNN] temporarily disable memory in backend

- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
The following piece of code is allowed now (notice the measurement in cr1[0] for both qubits):
{code}
circ1 = QuantumCircuit(qr1, qr2, cr1, cr2)
circ1.h(qr1[0])
circ1.h(qr2[0])
circ1.measure(qr1[0], cr1[0])
circ1.h(qr2[0])
circ1.measure(qr2[0], cr1[0])
{code}
> [DEM-738] qiskit backend change to allow re-use of classical bits

- docs/example_qiskit_entangle.py
- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
Realisation to view the QI histogram in the result. This histogram exists of probabilities for the states after the 'translation' of the qubit registers to classical bit measurements, so for the Qiskit user it is clear what the probabilities are representing.
I asked the Qiskit people where to put these probability-results and they said to put it in probabilites under result.data, so result.data.probabilities.
Within the unittests of this tickets, the probabilities are checked against the expected probabilities. Meaning floating point comparison, meaning carefulness. I used isclose() from numpy to check equality of floats.
> [DEM-735] implementation of full state histogram

- src/quantuminspire/qiskit/circuit_parser.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
In this change the circuit u3, u2, u1 and u are fixed.
u3 was wrong in 2 ways, the parameter for the Ry gate is the first. Also the gates must be added in reversed order to match the matrix multiplication for u3 (U3(theta, phi, lambda) = Rz(phi)Ry(theta)Rz(lambda))
u2 and u1 were only defined for a number of fixed rotations. With the fix of u3 now all rotations for these gates are supported because U1(lambda) = U3(0, 0, lambda) and U2(phi, lambda) = U3(pi/2, phi, lambda).
The u gate is equal to the u3 gate.
When u1 and u2 are transformed to a call for u3, parameters are added  in both params and texparams fields of the circuit (a temporary so no effect on the caller). Within _u3 there is no difference if the call was directly from a u3 gate or a transformed u2/u1.
The unit tests have been …
> fixed the gates u3, u2, u1 and u

- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
With this issue, the raw data that is returned from the backend is taken as the source to calculate the count histogram (instead of the probabilities histogram). Also the memory data field is filled with the raw data values.
A special case is when number_of_shots = 1. In this case the backend doesn't return raw_data.
With number_of_shots = 1, there must be one value in the counts histogram (with count = 1), and the same single value in memory data. To determine this value a random float is generated in the range [0, 1). With this random number the value from the probabilities histogram is taken where the added probabilities is greater this random number.
Also the unit tests are adjusted because the single shot unit test now delivers valid data.
Some minor docstring adjustments for the …
> Generating count histogram from the raw data

- src/quantuminspire/api.py
- src/quantuminspire/job.py
- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/test_api.py
- src/tests/quantuminspire/test_job.py
* Api.get was 'misused' for getting information from the backed. Now it is used once for getting the schema only.
* Api._get is now private method of Api
* Added public methods to Api to get the available information from the backend
* Restructured the unit tests for the code and functions where api.get was used and now another api-method is used.
* Added unit tests for the Api methods I added to get data from the backend now the get method is private.
> [DEM-811] api._get made private

- docs/example_projectq.ipynb
- docs/example_projectq_entangle.py
- docs/example_projectq_grover.py
- src/quantuminspire/projectq/backend_qx.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
It was obligatory (by our backend) to define a mapper for using projectq with the SDK. Therefore in our examples a manual mapper is added as an engine to use our backend. In essence this manual mapper mapped logical bit with number n to physical bit with number n.
Any other type of mapper can be used (linear mapper etc). The main engine of projectq doesn't make it obligatory to install a mapper. When no mapper is installed there will be no mapping of physical to logical qubits. In our backend this is now also the default behaviour, when no mapper is added the logical bitnumber becomes the physical bitnumber. This is the same behaviour as the manual mapper used earlier. Earlier when no mapper was detected our backend generated an exception.
Some unit tests are added, to test the default …
> [DEM-537] No manual mapper needed

- README.md
- docs/example_projectq_entangle.py
- docs/example_projectq_grover.py
- docs/example_qiskit_entangle.py
- src/quantuminspire/api.py
- src/quantuminspire/credentials.py
- src/tests/quantuminspire/test_api.py
- src/tests/quantuminspire/test_credentials.py
* More IBM like interface. Instead of <operation>_token, the interface now uses <operation>_account.
* Added enable_account (to set the environment during the session), delete_account, store_account (prevent overwriting earlier stored token), reversed the load order of load_account: first environment, second from file.
* Added unittests for the new functionality
* Prepared the README.md with a paragraph "Configure your token credentials for Quantum Inspire (expected soon)" how to use the token credentials in quantum inspire.
* Adjusted the examples to use the new interface (load_account instead of load_token)
> [DEM-757] token reprise

- src/quantuminspire/projectq/backend_qx.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
* Cleaned up the cqasm code generation a bit. Inconsistent lower and upper case cqasm was generated. According to the definition of cQASM v1.0 all commands are lower case (the gates are upper case in general).
* Tdag and Sdag were handled differently, one with a look up translation table, the other one directly. I removed the need for a lookup table.
* Unit tests are adjusted accordingly. The tdag code generation was tested twice, removed one.
> [DEM-868] ProjectQ Swap cQASM

- src/quantuminspire/api.py
- src/quantuminspire/exceptions.py
- src/quantuminspire/projectq/backend_qx.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
- src/tests/quantuminspire/test_api.py
* No api needed when creating QIBackend.
* In QIBackend, try to construct default QuantumInspireApi when no Api is passed to the constructor.
* When something goes wrong, overrule the technical message with a meaningful message what to do.
* Unit tests adjusted.
> [DEM-867] QIBackend creation with all defaults

- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
* Adjusted validation method in qiskit backend_qx (__validate_no_usage_after_measure)
* docstring was not correct
* added a check that measured memory bits are not used later on as a condition in a binary controlled gate. Because in FSP simulation measurements are not done until the end, so we can't make usage of measured classical bits to influence the outcome of a circuit yet.
* Unittests added
> [DEM-959] Validate usage of classical bits after measurement

- src/quantuminspire/api.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/quantuminspire/qiskit/qi_job.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
- src/tests/quantuminspire/test_api.py
The following general rules are implemented for both Qiskit and ProjectQ (another PR):
* An algorithm without measurements or only measurements at the end (no gates following the measurements) can be executed as full state projection, otherwise it is executed as non-fsp.
* Also in a non-fsp algorithm not more than one different qubits may be measured to a classical bit and a qubit may not be measured to more than one classical bit.
* When a non-fsp algorithm is run the warning as specced in the desired outcome of the ticket [DEM-944] should be printed, according to the acceptance criteria. In api there is a method to enable or disable this warning:
show_fsp_warning(self, enable: bool = True)
[DEM-944]: https://qutech-sd.atlassian.net/browse/DEM-944
> [DEM-944] fsp vs non-fsp in qiskit

- README.md
- src/quantuminspire/projectq/backend_qx.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
* When the maximum number of qubits for the simulator is reached, de-allocate qubits are reused.
* When a qubit is reused, a prep_z is added for this qubit. This prep_z is composed of a measurement of this qubit, followed by a conditional X on this qubit
* The allocation and deallocation is adjusted, so we keep track of the allocation of a physical bit to a simulation bit.
* When the backend is a hardware backend, the ancilla bits are NOT re-used.
> [DEM-1016] Reuse ancilla qubits

- src/quantuminspire/qiskit/circuit_parser.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
* Circuit parser casting of (rotation) parameters for formatting sympy classes from Qiskit
* Added unit tests
* Unit test parameters for all tests are converted to the real Qiskit parameters
* deleted 'texparams'. They are not in Qiskit anymore.
> [DEM-1057] error in circuit parser

- README.md
- src/quantuminspire/api.py
- src/quantuminspire/job.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/qi_job.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
- src/tests/quantuminspire/test_api.py
* At two places (api and qi_job) the loop is now also ended when other 'job final states' are received as status.
* Unit tests for these 'final state' status values added.
> [DEM-1172] Endless waiting for job

- src/quantuminspire/api.py
- src/tests/quantuminspire/test_api.py
* Removing heading and trailing spaces and tabs
* unit test added. Had to add the params-parameter to the mock to store the assets-content
* The prove that a circuit with unindented sub-circuits is running correctly is given in the demo
> [DEM-1186] stripping spaces and tabs from qasm

- src/quantuminspire/api.py
- src/tests/quantuminspire/test_api.py
* When create job fails or another error (e.g. from coreapi) occures when executing qasm, instead of passing the coreapi exception to the user we package it in the result (no histogram, raw text explaining what happened)
* Added unit tests
> [DEM-1185] Result generates nice error when creating job fails

- .pylintrc
- README.md
- docs/example_projectq_entangle.py
- docs/example_qiskit_entangle.py
- src/quantuminspire/api.py
- src/quantuminspire/credentials.py
- src/quantuminspire/projectq/backend_qx.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/qi_result.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
- version.py
* When using Qiskit, now also Quantum Inspire project names can be set
* When no project name is set, a default is taken
* When an existing project name is chosen, the experiments are added to the existing project
* qi_job.result() now has a parameter to only fetch the results for the latest run (instead ALL results for the project)
> [INS-126] Project names in Qiskit

- .readthedocs.yml
- docs/examples/example_projectq.ipynb
- docs/examples/grover_algorithm_qi.ipynb
- docs/examples/qi-performance-test.ipynb
- docs/introduction.rst
- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Adjusted readthedocs for using version 3.8 of python
* Fix for damaged projects when error occured while post-processing the cQASM algorithm
* Check added during pre-processing for experiments where the number of classical bits is not enough to hold the measured qubits
* Removed format_vector method not used in notebook
* Renamed IPython to Jupyter
> [SDS-301] Fix for damaged projects and not enough classical bits

- src/quantuminspire/api.py
- src/tests/quantuminspire/test_api.py
* Added method to get calibration info to api
* Added unit tests
> [SDS-307] Now able to get calibration data from result

- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/qi_result.py
- src/tests/quantuminspire/qiskit/test_qi_result.py
A minimal example:
```
import quantuminspire
from quantuminspire.credentials import get_authentication
from quantuminspire.qiskit import QI
from qiskit.circuit import QuantumCircuit
from qiskit import execute
qc=QuantumCircuit(2,2)
qc.h(0)
qc.cz(0,1)
qc.measure_all()
qc.draw()
authentication = get_authentication()
QI.set_authentication(authentication)
api = QI.get_api()
backend = QI.get_backend("Starmon-5")
job = execute(qc, backend)
result = job.result()
calibration = result.get_calibration(api)
print(calibration)
```
@QFer Not sure how to test this, since in the tests we have no active backends I think.
> [SDS-NNN] Calibrations in result

- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Added status() to backend to return the BackendStatus
* pending jobs are not known. We leave it 0 because Qiskit doesn't accept negative values.
* backend_version is not coming from the backend, currently SDK version is taken as backend version
> [SDS-NNN] Backend status

- .travis.yml
- src/quantuminspire/api.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Switch to Qiskit classes for (soon) deprecated classes:
* BaseBackend -> BackendV1
* BaseProvider -> ProviderV1
* BaseJob -> JobV1
* in Travis sudo argument is not supported anymore - deleted from travis.yml
* Solved pylint error for api warning log message using f-string
> [SDS-424] Qiskit upstream changes

- .travis.yml
* fixing the fact that pull requests from forked repositories are failing on the examples because travis doesn't expose the token there
* The examples should always run on dev branch and when it is not a pull request
> [SDS-NNN] travis pull request

- .github/workflows/nightly.yaml
* Python 3.7 instead of 3.6 (for qiskit terra)
> [SDS-NNN] Nightly build switch to python 3.7 (min. version for qiskit)

- .coveragerc
- src/quantuminspire/job.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/qi_job.py
Postponed annotations allow us to use forward code references without having access to them statically, but we can have access at runtime. Using the TYPE_CHECKING constant from typing makes sure that we don't have circular dependencies in the actual code.
The "correct" approach would be to extract interfaces. For example, we could have a generic API interface or a generic Job interface that exposes the methods and properties that we need access to. However, this is not particularly "Pythonese", so this approach seemed more lightweight.
> [SDS-335] Resolve import cycles using postponed annotations

- src/quantuminspire/api.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/quantuminspire/qiskit/measurements.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
- src/tests/quantuminspire/qiskit/test_measurements.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
* Fixes https://github.com/QuTech-Delft/quantuminspire/issues/134
* Refactored measurement to a separate class and added measurement functionality to this class
* The fix itself is mainly situated in the call to measurements.get_qreg_for_conditional_creg in circuit_parser._parse_bin_ctrl_gate
* Added/adjusted unit tests
> [SDS-540] fix for non-lineair measured bits used in conditional

- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Assumed 'empty' raw data list was wrong. The multi measurement empty raw_data_list is [[]] instead of []
* Adjusted test cases
* Bug fixed. First check to see if there is a list of lists and then if the first list is filled with data
> [SDS-794] Check for raw data list was wrong

- .github/workflows/nightly.yaml
This PR updates the GitHub Actions versions. In addition:
* It replaces the outdated BSFishy/pip-action (not updated in the last 3 years) by a simple run.
* It adds a dependabot file to automatically update GitHub actions going forward.
> [SDS-808] Update GitHub actions versions

- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Convert `device dependent` run-parameter allow_fsp to bool when it is a string (used the strtobool implementation distutils)
> [SDS-981] Argument type check
