QuTech-Delft/quantuminspire

- README.md
- src/quantuminspire/api.py
- src/tests/quantuminspire/test_api.py
Added docstrings and revised docstring for all methods of Api.
Updated the unittests with some minor changes I made for getting consistency in output/interface etc.
> [DEM-780] added docstring to ApiQI

- src/quantuminspire/api.py
- src/quantuminspire/job.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
- src/tests/quantuminspire/test_job.py
Type hints added in all files but projectq backend because it is in progress in another branch.
Mypy is satisfied except for missing external imports (Class cannot subclass 'blabla' (has type 'Any'))
> [DEM-NNN] type hinting

- docs/example_projectq_entangle.py
- docs/example_projectq_grover.py
- docs/example_qiskit_entangle.py
- docs/grover_algorithm_qi.ipynb
- docs/qi-performance-test.ipynb
- src/quantuminspire/api.py
- src/quantuminspire/credentials.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
- src/tests/quantuminspire/test_api.py
- src/tests/quantuminspire/test_credentials.py
* TokenAuthentication possible besides BasicAuthentication
* Python examples adjusted, depending on environment variables the right authentication is created. when no environment is set, BasicAuthentication is default.
* Docstring adjusted
* Unittests adjusted and added
> [DEM-757] token authentication

- .travis.yml
- setup.py
* matplotlib and jupyter both dependencies in setup instead of separate install because the notebooks need them to run.
* install mypy
* run mypy
* Increased time-out of the notebook tests because of the performance of the staging-environment.
> [DEM-870] Mypy in travis

- setup.py
* Adjustment for compatible qiskit versions
> [DEM-NNN] version check for Qiskit in setup

- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
* Added max_experiments to configurational. It is an optional but necessary for aqua.
* texparams in QasmInstructions are gone with qiskit terra 0.8.0.
> [DEM-942] Fix for Qiskit Aqua VQE

- requirements.txt
* Requirements.txt is needed for mybinder to install projectq and Qiskit.
* Adjusted requirements.txt. Only projectq and qiskit dependencies without version numbers. When merged in master Mybinder will build the master branch against the latest version of qiskit/projectq.
> [DEM-851] Mybinder revise

- README.md
* Link changed as stated in the mybinder bug report
> [DEM-1092]Mybinder 404 not found

- docs/classifier_example/classification_example3_4_features.ipynb
Another use of deprecated plot_state
> [DEM-1093] plot_state deprecated in Qiskit

- src/quantuminspire/api.py
- src/quantuminspire/job.py
- src/quantuminspire/projectq/backend_qx.py
- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_circuit_parser.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
- src/tests/quantuminspire/test_api.py
- src/tests/quantuminspire/test_job.py
* Full state projection defaults to False for algorithms executed directly (without projectQ/Qiskit backend)
* Added some missing license headers
* Reordered some imports
* Solved python code inspection warning
> [DEM-1194] Full state projection

- src/quantuminspire/api.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/test_api.py
* Check if we are running on a hardware backend before printing the non-optimization message.
* Test added that no message is printed on hardware backend.
> [DEM-1418] No message about non-optimized experiments on hardware backends

- src/quantuminspire/api.py
* updated the docstring-descriptions of the api structures in some methods
> [DEM-1447] updated the descriptions of the api structures

- src/quantuminspire/qiskit/qi_job.py
* Fix for missing job parameter in backend result method
> [INS-NN] Fix for missing parameter

- src/quantuminspire/api.py
- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/test_api.py
* Full state projection is never True for a created job that runs on hardware
* Fixed a mypy error
> [SDS-242] Optimized-flag not valid for hardware

- docs/projectq.rst
- docs/qiskit.rst
- src/quantuminspire/exceptions.py
- src/quantuminspire/job.py
- src/quantuminspire/projectq/backend_qx.py
- src/quantuminspire/qiskit/backend_qx.py
- src/quantuminspire/qiskit/circuit_parser.py
- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/qi_result.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_qi_result.py
* Added explanation of relation between QIJob (Qiskit job) and Quantum Inspire project and Qiskit circuit and Quantum Inspire job.
* Solved some small issues in the generated documentation.
* Consistent naming in documentation
* Some more Qiskit and ProjectQ renaming done
> [SDS-NNN] Some documentation improvements

- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
* Ability to get the api from the QI-quantum inspire provider when using Qiskit
* Unit tests
> [SDS-NNN] Get API from provider

- src/quantuminspire/qiskit/qi_job.py
- src/quantuminspire/qiskit/qi_result.py
- src/quantuminspire/qiskit/quantum_inspire_provider.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
- src/tests/quantuminspire/qiskit/test_quantum_inspire_provider.py
* Fixed coupling map type
* Added queue_position method to job for queued jobs
* Calculate total time taken for all jobs in result
> [SDS-423] Coupling map qiskit

- src/quantuminspire/api.py
- src/quantuminspire/qiskit/backend_qx.py
- src/tests/quantuminspire/projectq/test_backend_qx.py
- src/tests/quantuminspire/qiskit/test_backend_qx.py
- src/tests/quantuminspire/test_api.py
- src/tests/quantuminspire/test_job.py
* Replaced OrderedDict with dict, reformatting changed code
> [SDS-435] OrderedDict not needed

- .github/workflows/nightly.yaml
* Example files were moved to subdirectory examples
> [SDS-NNN] Nightly uses wrong directory for examples files

- README.md
- docs/_static/theme_overrides.css
- docs/conf.py
- docs/introduction.rst
* Changes in conf.py and css file in _static\theme_overrides to:
* display correct html output
* correct for the wide tables
> [SDS-NNN] Changes needed to display correct html again

- src/quantuminspire/api.py
- src/tests/quantuminspire/test_api.py
* Job delete api returns None
* Test adjusted
> [ISSUE-128] job delete

- src/quantuminspire/qiskit/qi_job.py
- src/tests/quantuminspire/qiskit/test_qi_job.py
* Fix for issue https://github.com/QuTech-Delft/quantuminspire/issues/132
* Added test case
* Adjusted some other test cases (had some unneeded lines of code)
> [SDS-542] Fix for serializable status-field in result

- .github/workflows/nightly.yaml
- setup.py
* removed package sklearn from setup, unused
* fix in workflow nightly.yaml
> [SDS-826] unused package breaks nightly

- .github/workflows/nightly.yaml
* Split cleanup from running the examples in the nightly as a separated step
> [SDS-NNN] split cleanup task

- .readthedocs.yml
* Fixed wrong readthedocs path in readthedocs.yml
> Wrong readthedocs path
